### ISSUE TITLE
The forum's time may not align with user's actual time zone.

### ISSUE THREAD

**Issue by wangsnuxiao** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#134]
Great progress on your web application! 
Here might be an issue you want to watch out is that in the forum's comments section you will show the time and date the comments have been made. This is a great feature. However, you might want to be aware of the time zone's difference.

Here is an example: The test has been conducted on Nov 18 4:03.
![Screen Shot 2021-11-18 at 4 09 30 PM](https://user-images.githubusercontent.com/19668357/142497163-b906d828-75dd-48bd-8d14-ab4ac6796fa8.png)

The time recorded was 9:03.

Potential solution:
1) record users' service area at the time of their registration. Render the time based on their timezone.

2) Detect users' timezone dynamically by using their accessing IP address.

**Comment by MengZhou11** [comment]
Hi, thanks for ur comment. That's a good idea. However, at this moment fixing time zone issue is not under our plan. Thanks again!
