### ISSUE TITLE
Non numeric telephone number and dob range

### ISSUE THREAD

**Issue by Scott-Canning** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#138]
Site looks great! Some minor things I've found thus far:

While limited in size, the telephone field will take input of almost any type. As someone prior to me pointed out, you can future date the DOB field but you can also go fairly historic; this goes for profile updates and account registrations.

![image.png](https://images.zenhubusercontent.com/614dcca8f2879f4a3e254cbb/72dfc770-2063-448e-8517-0019e47ce422)

![image](https://user-images.githubusercontent.com/34758484/142527689-8a89fa03-037e-4d0b-815e-3df6b39d33a0.png)

![image](https://user-images.githubusercontent.com/34758484/142528672-1651ba72-dbed-4322-b71c-5d6976e5ca49.png)

**Comment by barksdaleaz** [comment]
Noticed this as well - also a person can edit their profile to have a DOB that doesn't make sense (like Scott mentioned). Maybe there should be an age limit/restriction? Doesn't make sense for a person who was born in 2021 to be able to create an account/use this site.
