### ISSUE TITLE
Accounts not properly linked 

### ISSUE THREAD

**Issue by HenryTseTse** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#141]
**I made an appointment using provider_test5**
![Screen Shot 2021-11-18 at 8 55 42 PM](https://user-images.githubusercontent.com/33527580/142551675-564eede8-588a-42cd-b6e2-db7631e92d7d.png)

**I went on patient_test5 to accept the appointment**
![Screen Shot 2021-11-18 at 8 56 25 PM](https://user-images.githubusercontent.com/33527580/142551740-9ef94f48-7ffa-48c3-8576-430c91303739.png)

**Appointment does not show up for patient_test5**
![Screen Shot 2021-11-18 at 8 56 30 PM](https://user-images.githubusercontent.com/33527580/142551779-263269f8-0622-4cd0-baf7-77ea689a79ac.png)

**Appointment instead shows up for patient_test1 instead of patient_test5**
![Screen Shot 2021-11-18 at 9 00 03 PM](https://user-images.githubusercontent.com/33527580/142551892-475d71c5-b8b0-42c7-bc7e-11f1df852d90.png)

**Comment by MengZhou11** [comment]
Hi, thanks for your feedback. The provider cannot make appointment with patient, only from the patient side, users are able to reserve appointment.
