### ISSUE TITLE
Upcoming appointments not showing up 

### ISSUE THREAD

**Issue by ssingh1997** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#143]
So this bug would be easier to show if I could record but I basically created a new time slot from the provider's end. I then logged in as a patient and reserved that new time slot. However, I do not see the new appointment on my home page. Also the appointment that is showing up on my profile page does not show up under upcoming appointments under the bookings tab. 

![image](https://user-images.githubusercontent.com/39809317/142553253-2a2c29b0-eb85-4494-a57c-a7d6a2f13183.png)
New appointment does not show up here

![image](https://user-images.githubusercontent.com/39809317/142553330-bea2b348-fb87-4c0c-984f-b4148260ecb7.png)
both upcoming appointments not showing up under "Upcoming appointments"

**Comment by MengZhou11** [comment]
Hi, thanks for feedback. At that point we did not have it available. Now it is on. I am going to close this issue. Thanks
