### ISSUE TITLE
Able to edit profile by entering 2 digits in phone number. Please see the SS

### ISSUE THREAD

**Issue by VISHDIVGAU** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#148]
![team1issue1.png](https://images.zenhubusercontent.com/614e108cc19f8ac004baa3cc/968eebb3-c384-4fe0-9e9c-7819cdc1b040)

**Comment by jgingh7** [comment]
In addition, saving alphabets are working too
![image](https://user-images.githubusercontent.com/60978943/142701926-7ac7034c-a1b7-4626-aae3-9393a2707842.png)

**Comment by MengZhou11** [comment]
Fixed!
