### ISSUE TITLE
Difficulty submitting New Appointment Form as provider

### ISSUE THREAD

**Issue by marcuspoon2** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#160]
It's difficult to create a new appointment as a provider. There is no guidance on what makes a proper date, start/end time, and meeting link. They all require specific patterns to follow but you're left to guess as to what qualifies as 'right'. In addition, 1:00 in the form translates to 1:00am which should not be expected behavior 

Recreate:
1. Log in as a provider
2. Go to Booking -> New Slot
3. Enter 'www.zoom.com' in 'meeting link'. This is a correct url, but the website requires an 'https://'
<img width="326" alt="Screen Shot 2021-11-19 at 1 19 04 PM" src="https://user-images.githubusercontent.com/67922103/142672079-67da1392-00c1-4d59-bc20-31dacdbfdfe1.png">
4. enter '20/10/1990' in Date. This follows dd/mm/yyyy format but the field requires mm/dd/yyyy, this should be stated.
5. The times also require the full analog version, and won't accept things like 1 pm
<img width="371" alt="Screen Shot 2021-11-19 at 1 21 50 PM" src="https://user-images.githubusercontent.com/67922103/142672420-3fa4ce7b-871b-47e8-b52d-bc486f15a435.png">

**Comment by helicopta** [comment]
fixed in sprint 10.
