### ISSUE TITLE
Bug: Text for Back to Forum button is outside of the button

### ISSUE THREAD

**Issue by susmitabhowmik** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#162]
When logged in as a provider, and selecting the Back to Forum button, the text for the button seems to be going outside of the button container.

![Screen Shot 2021-11-19 at 1 58 55 PM](https://user-images.githubusercontent.com/21378515/142676737-9d97e991-cd8c-421c-b7a6-139dbfe96d83.png)

**Comment by helicopta** [comment]
i dont recall there is a "button" for "back to forum"....weird bug.....
