### ISSUE TITLE
Displayed user name conflicts with edited profile page name

### ISSUE THREAD

**Issue by azraf-a** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#163]
Description:
I can update the name for a given user on the profile but it seems like the landing and rest of the app does not update accordingly.

Produced on account test5, with name set to Stack Trooper.

Images attached
<img width="960" alt="bug_team1" src="https://user-images.githubusercontent.com/69122096/142691798-eaba3480-41a6-4b04-980c-70a06df04639.PNG">
<img width="960" alt="bug_team1_1" src="https://user-images.githubusercontent.com/69122096/142691800-c07920e8-19f0-4611-a24e-a83185857290.PNG">
.

**Comment by MengZhou11** [comment]
Hi thanks for your feedback, however in our website, the username is not changeable. The first name and last name is user information. That's why when you update first and last name, it did not conflict to your profile page.
