### ISSUE TITLE
bug: can't make a new appointment after an invalid input value

### ISSUE THREAD

**Issue by wanghaox2020** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#166]
![team1_issue](https://user-images.githubusercontent.com/79470452/142699765-fdef6518-3989-4be0-b595-5b37a8508f87.PNG)
if I enter an invalid day or time, like 2021-11-32, and start at 25:00 pm to 26:00 pm, it will give an invalid time, which is great, but after I correct it, I see the same result above. 
can't save it.

**Comment by helicopta** [comment]
This situation should not happen....
