### ISSUE TITLE
Missing an epic

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#2]
<img width="771" alt="Screen Shot 2021-09-28 at 17 39 40" src="https://user-images.githubusercontent.com/53953892/135169603-ecefd311-3a34-4cfd-958a-4b882a2f079a.png">

In the High Level Analysis there seems to be a missing epic.
How does the data from NYC Mental Provider's Info Open Database gets into "Providers list with availability"?  
The database is not an actor yet it shows up, please clarify

**Comment by helicopta** [comment]
Indeed we don't need to access any database, our project is a platform that lets providers register. We are going to remove this part in the high-level analysis diagram.
