### ISSUE TITLE
Integrating templates created by Aayushi to auth-no-api backend

### ISSUE THREAD

**Issue by jl12182** [gcivil-nyu-org/Team_Team1_CS-GY-6063-Fall2021#45]

**Comment by MengZhou11** [comment]
User story
Integrating templates created by Aayushi to auth-no-api backend

Acceptance criteria
The sign up and log in pages with appropriate authentication

Definition of Done
Combine Aayushi's frontend with backend code, the web should be able to ran on local with basic sign up and login function
